name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.0.1]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ npm 12.2 }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ nodejs-cli }}

    - name: Build
      run: |
        npm install
        npx webpack
